update install script

diff --git a/linux/install_script b/linux/install_script
--- a/linux/install_script
+++ b/linux/install_script
@@ -1,69 +1,130 @@
 #!/bin/bash
 
 set -e # exit when a cmd fails
-set -x # print cmd before running it
+#set -x # debug, print cmd before running it
 
-# update the package database
-sudo pacman -Syy
+# ------------------------------------------
+echo "Updating Package Database..."
+# ------------------------------------------
+sudo pacman -Sy
 
-# AUR
-sudo pacman -S yay
+if ! command -v yay &>/dev/null; then
+  echo "'yay' command not found. Installing yay..."
+  pacman -S --needed git base-devel &&
+    git clone https://aur.archlinux.org/yay.git &&
+    cd yay &&
+    makepkg -si
+fi
 
-# cli tools
-sudo pacman -S ack
-sudo pacman -S curl
-sudo pacman -S fd
-sudo pacman -S jq
-sudo pacman -S less
-sudo pacman -S stow
-sudo pacman -S tldr
-sudo pacman -S trash-cli
-sudo pacman -S tree
-sudo pacman -S wget
-sudo pacman -S xsel
-sudo pacman -S z
+# ------------------------------------------
+echo "Installing CLI Tools..."
+# ------------------------------------------
 
-# programming tools
-sudo pacman -S git
-sudo pacman -S docker
-systemctl enable docker.service
-sudo pacman -S lazygit
-sudo pacman -S lazydocker
-sudo pacman -S ripgrep
-sudo pacman -S neovim
-yay -S asdf-vm.git
+sudo pacman -S --needed \
+  base-devel \
+  fd \
+  jq \
+  less \
+  stow \
+  tldr \
+  trash-cli \
+  tree \
+  wget \
+  z \
+  ;
 
-# language support
-# sudo pacman -S opam
-# see asdf readme for erlang install on arch
+# ------------------------------------------
+echo "Installing Programming Tools..."
+# ------------------------------------------
 
-# --------- Desktop environment
-sudo pacman -S flatpack
-yay -S ttf-ms-fonts
-sudo pacman -S adobe-source-sans-fonts
-sudo pacman -S ttf-open-sans
-flatpak install chrome
-flatpak install datagrip
+sudo pacman -S --needed \
+  docker \
+  fzf \
+  git \
+  lazygit \
+  neovim \
+  ripgrep \
+  opam \
+  ;
 
-# gnome desktop
-yay -S ulauncher
-yay -S gnome-shell-extension-forge
-yay -S gnome-shell-extension-space-bar
-# gnome themes
-sudo pacman -S gnome-browser-connector
+if ! systemctl is-active --quiet docker.service; then
+  echo "Enabling & starting docker.service"
+  systemctl enable docker.service
+  systemctl start docker.service
+fi
+
+yay -S --needed \
+  asdf-vm \
+  lazydocker \
+  ;
+
+# ------------------------------------------
+echo "Installing Languages..."
+# ------------------------------------------
+
+sudo pacman -S --needed opam
+yay -S --needed asdf-vm
+
+# ------------------------------------------
+echo "Installing Desktop Env..."
+# ------------------------------------------
+
+sudo pacman -S --needed \
+  adobe-source-sans-fonts \
+  bluez \
+  bluez-utils \
+  flatpak \
+  keyd \
+  wl-clipboard \
+  ;
+
+yay -S --needed \
+  ttf-ms-fonts \
+  ulauncher \
+  ;
+
+if ! systemctl is-active --quiet bluetooth.service; then
+  echo "Enabling & starting bluetooth.service"
+  systemctl enable bluetooth.service
+  systemctl start bluetooth.service
+fi
+
+# ------------------------------------------
+echo "Installing Flatpak apps..."
+# ------------------------------------------
+
+is_installed() {
+  flatpak list | grep -q "$1"
+}
+
+if ! is_installed "com.google.Chrome"; then
+  flatpak install -y flathub com.google.Chrome
+fi
+
+if ! is_installed "com.jetbrains.DataGrip"; then
+  flatpak install -y flathub com.jetbrains.DataGrip
+fi
+
+# ------------------------------------------
+echo "Done!"
+# ------------------------------------------
+
+# legacy gnome desktop
+# yay -S gnome-shell-extension-forge
+# yay -S gnome-shell-extension-space-bar
 
 # --------- Setup framework13
 
-COMPUTER_MAKER=$(sudo dmidecode -t system | grep 'Manufacturer:' | awk '{print $2}')
-
-if [ "$COMPUTER_MAKER" == "Framework" ]; then
-	# enable intercept plugin
-	# https://wiki.archlinux.org/title/Interception-tools
-	sudo pacman -S interception-tools interception-caps2esc
-	systemctl enable udevmon
-
-	sudo pacman -S bluez bluez-utils
-	sudo systemctl enable bluetooth
-	# https://wiki.archlinux.org/title/Network_configuration/Wireless#Respecting_the_regulatory_domain
-	sudo pacman -S wireless-regdb
-fi
+# COMPUTER_MAKER=$(sudo dmidecode -t system | grep 'Manufacturer:' | awk '{print $2}')
+# if [ "$COMPUTER_MAKER" == "Framework" ]; then
+#   # enable intercept plugin
+#   # https://wiki.archlinux.org/title/Interception-tools
+#   sudo pacman -S interception-tools interception-caps2esc
+#   systemctl enable udevmon
+#
+#   sudo pacman -S bluez bluez-utils
+#   sudo systemctl enable bluetooth
+#
+#   # https://wiki.archlinux.org/title/Network_configuration/Wireless#Respecting_the_regulatory_domain
+#   sudo pacman -S wireless-regdb
+# fi
