update

diff --git a/linux/install_script b/linux/install_script
--- a/linux/install_script
+++ b/linux/install_script
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-set -e
-set -x
+set -e # exit when a cmd fails
+set -x # print cmd before running it
 
 # update the package database
 sudo pacman -Syy
@@ -40,7 +40,8 @@ yay -S asdf-vm.git
 # --------- Desktop environment
 sudo pacman -S flatpack
 yay -S ttf-ms-fonts
-flatpack install chrome
+flatpak install chrome
+flatpak install datagrip
 
 # gnome desktop
 yay -S ulauncher
@@ -54,7 +55,6 @@ sudo pacman -S gnome-browser-connector
 COMPUTER_MAKER=$(sudo dmidecode -t system | grep 'Manufacturer:' | awk '{print $2}')
 
 if [ "$COMPUTER_MAKER" == "Framework" ]; then
-
 	# enable intercept plugin
 	# https://wiki.archlinux.org/title/Interception-tools
 	sudo pacman -S interception-tools interception-caps2esc
